### PR TITLE
Update knative version to 1.9

### PR DESCRIPTION
**Pull request by anshalshukla**
## Summary

Regular Update. Updated the knative version.

### CODE REVIEW

**Comment by ustiugov** [comment]
@anshalshukla have you tested it with the workflow from the quickstart guide (with Firecracker and with containers)? Once you are done with testing, please ask @shyamjesal for a review.

**Comment by ustiugov** [comment]
I noticed that the wiki page by Shyam doesn't really say about which repo and branch of `serving` one needs to take. @shyamjesal, could you please clarify this on the wiki page?

One needs to copy and rebase the following branch in our fork of Knative: https://github.com/ease-lab/serving/pull/8

**Comment by shyamjesal** [comment]
Yes, that branch is correct, we need to update that branch and add the generated yamls.

**Comment by ustiugov** [comment]
@anshalshukla please follow the updated wiki

**Comment by anshalshukla** [comment]
Sure, I'll do it today

**Comment by ustiugov** [comment]
@shyamjesal wait a bit. Anshal needs to rebase the copied branch first.

**Comment by ustiugov** [comment]
@anshalshukla any updates on this PR?

**Comment by anshalshukla** [comment]
Updated knative using [this](https://github.com/ease-lab/serving/pull/9) branch

**Pull request closed without merging**
