### PR TITLE
fix the scikit-learn package name

### PR DESCRIPTION
**Pull request by niravnshah**
## Summary

package name for sklearn is changed to scikit-learn 

## Implementation Notes :hammer_and_pick:

* Briefly outline the overall technical solution. If necessary, identify talking points where the reviewer's attention should be drawn to.

## External Dependencies :four_leaf_clover:

* 

## Breaking API Changes :warning:

* 

*Simply specify none (N/A) if not applicable.*

### CODE REVIEW

**Comment by niravnshah** [comment]
image

**Comment by ustiugov** [comment]
@niravnshah thank you. Does the image build now?

**Comment by niravnshah** [comment]
> @niravnshah thank you. Does the image build now?

Yes, it does.

**Comment by ustiugov** [comment]
@niravnshah thank you for fixing this

**Pull request merged**
